<?php
return [
    'collections' => [
        ['name' => 'Atemporal', 'slug' => 'atemporal', 'description' => 'Piezas esenciales que trascienden temporadas. Diseños simples, cómodos y versátiles hechos para acompañarte todos los días.'],
        ['name' => 'Comodidad Moderna', 'slug' => 'comodidad-moderna', 'description' => 'Prendas relajadas con cortes actuales. Diseños que combinan ligereza y estilo para un día sin complicaciones.'],
        ['name' => 'Verano Libre (40%)', 'slug' => 'verano-libre-40', 'description' => 'Colores vibrantes y telas frescas para disfrutar cada día soleado. Piezas hechas para acompañarte en vacaciones y momentos al aire libre.'],
        ['name' => 'On Sale', 'slug' => 'on-sale', 'description' => 'Tus favoritos a precios irresistibles. Oportunidad de renovar tu guardarropa con básicos y tendencias al mejor valor.'],
    ],

    'products' => [
        // --- ATEMPORAL --- //
        [
            'name' => 'Blusa gráfica “Heart Tee”',
            'slug' => 'heart-tee',
            'description' => 'Blusa blanca con estampado gráfico, tela ligera y fresca ideal para looks casuales.',
            'price' => 499,
            'published' => true,
            'total_product_stock' => 15,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['atemporal'],
            'images' => ['catalog/atemporal/heart-tee.png'],
        ],
        [
            'name' => 'Camiseta deslavada “Olive Wash”',
            'slug' => 'olive-wash',
            'description' => 'Camiseta verde oliva con efecto deslavado, estilo urbano relajado.',
            'price' => 399,
            'published' => true,
            'total_product_stock' => 20,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['atemporal'],
            'images' => ['catalog/atemporal/olive-wash.png'],
        ],
        [
            'name' => 'Leggings deportivos “Soft Olive”',
            'slug' => 'soft-olive',
            'description' => 'Leggings en tono verde con líneas horizontales, perfectos para entrenar con estilo.',
            'price' => 599,
            'published' => true,
            'total_product_stock' => 12,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['atemporal'],
            'images' => ['catalog/atemporal/soft-olive.png'],
        ],
        [
            'name' => 'Pantalón chino “Classic Beige”',
            'slug' => 'classic-beige',
            'description' => 'Pantalón tipo chino en tono beige claro, ideal para atuendos casuales elegantes.',
            'price' => 899,
            'published' => true,
            'total_product_stock' => 10,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['atemporal'],
            'images' => ['catalog/atemporal/classic-beige.png'],
        ],
        [
            'name' => 'Sudadera deportiva “Run Black”',
            'slug' => 'run-black',
            'description' => 'Sudadera negra ligera, perfecta para entrenamientos o actividades al aire libre.',
            'price' => 699,
            'published' => true,
            'total_product_stock' => 8,
            'stock_status' => 'low_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['atemporal'],
            'images' => ['catalog/atemporal/run-black.png'],
        ],
        [
            'name' => 'Camiseta oversized “Urban Relax”',
            'slug' => 'urban-relax',
            'description' => 'Camiseta negra con corte amplio y estilo urbano relajado.',
            'price' => 499,
            'published' => true,
            'total_product_stock' => 18,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['atemporal'],
            'images' => ['catalog/atemporal/urban-relax.png'],
        ],
        [
            'name' => 'Camiseta blanca “Essential Tee”',
            'slug' => 'essential-tee',
            'description' => 'Camiseta blanca básica unisex, esencial en cualquier armario.',
            'price' => 399,
            'published' => true,
            'total_product_stock' => 25,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['atemporal'],
            'images' => ['catalog/atemporal/essential-tee.png'],
        ],
        // --- COMODIDAD MODERNA --- //
        [
            'name' => 'Camiseta relaxed “Autumn Breeze”',
            'slug' => 'autumn-breeze',
            'description' => 'Camiseta de algodón en tono marrón claro con corte relaxed fit, ligera y cómoda para uso diario.',
            'price' => 449,
            'published' => true,
            'total_product_stock' => 20,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['comodidad-moderna'],
            'images' => ['catalog/comodidad-moderna/autumn-breeze.png'],
        ],
        [
            'name' => 'Vestido minimal “Flow Sand”',
            'slug' => 'flow-sand',
            'description' => 'Vestido blanco minimalista con corte recto y tela transpirable, ideal para climas cálidos.',
            'price' => 899,
            'published' => true,
            'total_product_stock' => 12,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['comodidad-moderna'],
            'images' => ['catalog/comodidad-moderna/flow-sand.png'],
        ],
        [
            'name' => 'Sneakers neutros “Pure Step”',
            'slug' => 'pure-step',
            'description' => 'Sneakers blancos de suela ligera, estilo urbano minimalista en color blanco arena.',
            'price' => 1099,
            'published' => true,
            'total_product_stock' => 15,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['comodidad-moderna'],
            'images' => ['catalog/comodidad-moderna/pure-step.png'],
        ],
        [
            'name' => 'Rompevientos “Urban Shield”',
            'slug' => 'urban-shield',
            'description' => 'Rompevientos verde con tela ligera y elastano, pensado para proteger del viento con estilo moderno.',
            'price' => 1299,
            'published' => true,
            'total_product_stock' => 8,
            'stock_status' => 'low_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['comodidad-moderna'],
            'images' => ['catalog/comodidad-moderna/urban-shield.png'],
        ],
        [
            'name' => 'Joggers “Soft Move”',
            'slug' => 'soft-move',
            'description' => 'Joggers grises con corte tapered, fabricados en algodón suave y cómodo para uso diario.',
            'price' => 749,
            'published' => true,
            'total_product_stock' => 10,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['comodidad-moderna'],
            'images' => ['catalog/comodidad-moderna/soft-move.png'],
        ],
        [
            'name' => 'Sudadera oversized “Cloud Grey”',
            'slug' => 'cloud-grey',
            'description' => 'Sudadera gris claro oversized, 100% algodón, con un estilo relajado y moderno.',
            'price' => 699,
            'published' => true,
            'total_product_stock' => 14,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['comodidad-moderna'],
            'images' => ['catalog/comodidad-moderna/cloud-grey.png'],
        ],
        // --- VERANO LIBRE (40%) --- //
        [
            'name' => 'Bolsa de mano “Minimal Classic”',
            'slug' => 'minimal-classic-bag',
            'description' => 'Bolsa de mano con diseño minimalista. Promoción 40% de descuento (de $1,299 a $779). Compartimento principal amplio y correa ajustable.',
            'price' => 779,
            'published' => true,
            'total_product_stock' => 9,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['verano-libre-40'],
            'images' => ['catalog/verano-libre/minimal-classic-bag.png'],
        ],
        [
            'name' => 'Cadena “Luz Dorada”',
            'slug' => 'luz-dorada-chain',
            'description' => 'Cadena metálica tono dorado con acabado pulido. Promoción 40% de descuento (de $969 a $599). Cierre seguro tipo langosta.',
            'price' => 599,
            'published' => true,
            'total_product_stock' => 20,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['verano-libre-40'],
            'images' => ['catalog/verano-libre/luz-dorada-chain.png'],
        ],
        [
            'name' => 'Shorts rotos “Verano Libre”',
            'slug' => 'verano-libre-shorts',
            'description' => 'Shorts denim con acabado deshilachado. Promoción 40% de descuento (de $699 a $419). Cintura media y bolsillos funcionales.',
            'price' => 419,
            'published' => true,
            'total_product_stock' => 14,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['verano-libre-40'],
            'images' => ['catalog/verano-libre/verano-libre-shorts.png'],
        ],
        [
            'name' => 'Falda plisada “Cocoa Swing”',
            'slug' => 'cocoa-swing-skirt',
            'description' => 'Falda midi plisada en tono cacao, tela ligera con caída fluida y cintura elástica para mayor comodidad.',
            'price' => 419,
            'published' => true,
            'total_product_stock' => 9,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['verano-libre-40'],
            'images' => ['catalog/verano-libre/cocoa-swing-skirt.png'],
        ],
        // --- ON SALE --- //
        [
            'name' => 'Sudadera gris “Urban Chill”',
            'slug' => 'urban-chill-sweater',
            'description' => 'Sudadera gris de corte relajado, interior suave. Oferta (de $1,299 a $899). Capucha con ajuste y bolsillo tipo canguro.',
            'price' => 899,
            'published' => true,
            'total_product_stock' => 7,
            'stock_status' => 'low_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['on-sale'],
            'images' => ['catalog/on-sale/urban-chill-sweater.png'],
        ],
        [
            'name' => 'Tank top “Soft Touch”',
            'slug' => 'soft-touch-tank',
            'description' => 'Tank top con tacto suave y caída ligera. Oferta (de $399 a $299). Ideal para climas cálidos o para layering.',
            'price' => 299,
            'published' => true,
            'total_product_stock' => 16,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['on-sale'],
            'images' => ['catalog/on-sale/soft-touch-tank.png'],
        ],
        [
            'name' => 'Playera básica “Everyday fit”',
            'slug' => 'everyday-fit-tee',
            'description' => 'Playera básica de uso diario, corte clásico. Oferta (de $449 a $349). Tejido suave y transpirable.',
            'price' => 349,
            'published' => true,
            'total_product_stock' => 22,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['on-sale'],
            'images' => ['catalog/on-sale/everyday-fit-tee.png'],
        ],
        [
            'name' => 'Camisa blanca “Classic White”',
            'slug' => 'classic-white-shirt',
            'description' => 'Camisa de manga larga en algodón transpirable, corte slim, cuello clásico y puños ajustables. Ideal para oficina o eventos.',
            'price' => 899,
            'published' => true,
            'total_product_stock' => 12,
            'stock_status' => 'in_stock',
            'low_stock_threshold' => 5,
            'cached_quantity_sold' => 0,
            'collections' => ['on-sale'],
            'images' => ['catalog/on-sale/classic-white-shirt.png'],
        ],
    ],
];
